import express from 'express';
import {
  generateDemandLetter,
  autoGenerateDemandLetter,
  getDemandLetters,
  getDemandLetterById,
  downloadDemandLetter,
  getOverdueInvoices,
  updateDemandLetterStatus,
  deleteDemandLetter,
  batchGenerateDemandLetters
} from '../controllers/demandLetter.controller.js';
import { protect } from '../middleware/authMiddleware.js';
import { authorize } from '../middleware/roleMiddleware.js';

const router = express.Router();

// Apply auth middleware to all routes
router.use(protect);

// Generate demand letters (ADMIN/MANAGER only)
router.post(
  '/generate',
  authorize('ADMIN', 'MANAGER'),
  generateDemandLetter
);

// Auto-generate demand letter for tenant (ADMIN/MANAGER only)
router.post(
  '/auto-generate/:tenantId',
  authorize('ADMIN', 'MANAGER'),
  autoGenerateDemandLetter
);

// Note: batchGenerateDemandLetters function was not exported in the restructured controller
// If you need it, you'll have to add it back to the exports

// Get overdue invoices for a tenant
router.get(
  '/overdue-invoices/:tenantId',
  getOverdueInvoices
);

// Get all demand letters with filters
router.get(
  '/',
  getDemandLetters
);

// Get specific demand letter
router.get(
  '/:id',
  getDemandLetterById
);

// Download demand letter PDF
router.get(
  '/:id/download',
  downloadDemandLetter
);

// Update demand letter status (ADMIN only)
router.patch(
  '/:id/status',
  authorize('ADMIN'),
  updateDemandLetterStatus
);
// batch generate demand letters (ADMIN only)
router.post(
  '/batch-generate',
  authorize('ADMIN'),
  batchGenerateDemandLetters
);

// Delete demand letter (ADMIN only)
router.delete(
  '/:id',
  authorize('ADMIN'),
  deleteDemandLetter
);

router.get('/debug/user', protect, (req, res) => {
  res.json({
    success: true,
    user: req.user,
    userId: req.user?.userId,
    id: req.user?.id,
    role: req.user?.role
  });
});

export default router;