import express from 'express';
import {
  generateDemandLetter,
  autoGenerateDemandLetter,
  getDemandLetters,
  getDemandLetterById,
  downloadDemandLetter,
  getOverdueInvoices,
  updateDemandLetterStatus,
  deleteDemandLetter,
  sendDemandLetter,
  batchGenerateDemandLetters
} from '../controllers/demandLetter.controller.js';
import { protect } from '../middleware/authMiddleware.js';
import { authorize } from '../middleware/roleMiddleware.js';

const router = express.Router();

// Apply auth middleware to all routes
router.use(protect);

// ======================================================
// DEMAND LETTER GENERATION (Requires CREATE_DEMAND_LETTER permission)
// ======================================================

// Generate demand letter (ADMIN/MANAGER/USER with CREATE_DEMAND_LETTER permission)
router.post(
  '/generate',
  authorize('ADMIN', 'MANAGER', 'USER'),
  generateDemandLetter
);

// Auto-generate demand letter for tenant (Requires AUTO_GENERATE_DEMAND_LETTER permission)
router.post(
  '/auto-generate/:tenantId',
  authorize('ADMIN', 'MANAGER', 'USER'),
  autoGenerateDemandLetter
);

// Batch generate demand letters (Requires BATCH_GENERATE_DEMAND_LETTERS permission)
router.post(
  '/batch-generate',
  authorize('ADMIN', 'MANAGER', 'USER'),
  batchGenerateDemandLetters
);

// ======================================================
// DEMAND LETTER VIEWING (Requires VIEW_DEMAND_LETTERS permission)
// ======================================================

// Get all demand letters with filters
router.get(
  '/',
  authorize('ADMIN', 'MANAGER', 'USER'),
  getDemandLetters
);

// Get specific demand letter details (Requires VIEW_DEMAND_LETTER_DETAILS)
router.get(
  '/:id',
  authorize('ADMIN', 'MANAGER', 'USER'),
  getDemandLetterById
);

// Get overdue invoices for a tenant (Requires VIEW_OVERDUE_INVOICES)
router.get(
  '/overdue-invoices/:tenantId',
  authorize('ADMIN', 'MANAGER', 'USER'),
  getOverdueInvoices
);

// ======================================================
// DEMAND LETTER DOWNLOAD (Requires DOWNLOAD_DEMAND_LETTER permission)
// ======================================================

// Download demand letter PDF
router.get(
  '/:id/download',
  authorize('ADMIN', 'MANAGER', 'USER'),
  downloadDemandLetter
);

// ======================================================
// DEMAND LETTER UPDATES (Requires EDIT_DEMAND_LETTER_STATUS permission)
// ======================================================

// Update demand letter status
router.patch(
  '/:id/status',
  authorize('ADMIN', 'MANAGER', 'USER'),
  updateDemandLetterStatus
);

// ======================================================
// DEMAND LETTER DELETION (Requires DELETE_DEMAND_LETTER permission)
// ======================================================

// Delete demand letter
router.delete(
  '/:id',
  authorize('ADMIN', 'MANAGER', 'USER'),
  deleteDemandLetter
);

// ======================================================
// SEND DEMAND LETTER (Requires SEND_DEMAND_LETTERS permission)
// ======================================================

// Send demand letter to tenant (Add this endpoint if needed)
router.post(
  '/:id/send',
  authorize('ADMIN', 'MANAGER', 'USER'),
  sendDemandLetter // You'll need to implement this function
);

/* Debug route (remove in production)
router.get('/debug/user', protect, (req, res) => {
  res.json({
    success: true,
    user: req.user,
    userId: req.user?.userId,
    id: req.user?.id,
    role: req.user?.role
  });
});*/

export default router;